---
- name: Create Magento 2 installation parent folder.
  become: Yes
  file:
    group: "{{magento2_runtime_group}}"
    mode: 0755
    owner: "{{magento2_runtime_user}}"
    path: "{{ magento2_installation_parent }}"
    state: directory
  tags: ['file']

- name: Check if Magento 2 installation parent folder exists.
  stat:
    path: "{{ magento2_installation_parent }}"
  tags: ['stat', 'initialization']
  register: var_magento2_installation_parent

- name: Check if Magento 2 installation project folder exists.
  stat:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
  tags: ['stat', 'initialization']
  register: var_magento2_installation_name