---
- name: Create Magento 2 installation parent folder.
  become: Yes
  file:
    group: "{{magento2_runtime_group}}"
    mode: 0755
    owner: "{{magento2_runtime_user}}"
    path: "{{ magento2_installation_parent }}"
    state: directory
  tags: ['file']

- name: Check if Magento 2 installation parent folder exists.
  stat:
    path: "{{ magento2_installation_parent }}"
  tags: ['stat', 'initialization']
  register: var_magento2_installation_parent

- name: Check if Magento 2 installation project folder exists.
  stat:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
  tags: ['stat', 'initialization']
  register: var_magento2_installation_name

- name: Assert that Magento2 installation destination folder exists and is writeable.
  become_user: "{{ magento2_runtime_user }}"
  assert:
    that:
      - var_magento2_installation_parent.stat.exists
      - var_magento2_installation_parent.stat.writeable
  tags: ['assert', 'initialization']

# - name: Assert that Magento2 installation name folder doesn't exists.
#   assert:
#     that: not var_magento2_installation_name.stat.exists
#   tags: ['assert', 'initialization']