---
- name: Clone Magento 2 repository (with key).
  become_user: "{{magento2_runtime_user}}"
  git:
    accept_hostkey: Yes
    clone: yes
    dest: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    repo: "{{ magento2_installation_git_url }}"
    version: "{{ magento2_installation_git_version }}"
    key_file: "{{ magento2_installation_git_key }}"
  tags: ['git']
  when: magento2_installation_git_key != None

- name: Clone Magento 2 repository (without key).
  become_user: "{{magento2_runtime_user}}"
  git:
    accept_hostkey: Yes
    clone: yes
    dest: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    repo: "{{ magento2_installation_git_url }}"
    version: "{{ magento2_installation_git_version }}"
  tags: ['git']
  when: magento2_installation_git_key == None

- name: Set proper ownwernship of repository files.
  file: 
    group: "{{magento2_runtime_group}}"
    mode: 0775
    owner: "{{magento2_runtime_user}}"
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    recurse: Yes
    state: directory
  tags: ['file']

- name: Update Magento 2 project.
  become_user: "{{magento2_runtime_user}}"
  composer:
    command: update
    working_dir: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
  tags: ['composer']
