---
- name: Clone Magento 2 repository.
  become_user: "{{magento2_runtime_user}}"
  git:
    accept_hostkey: Yes
    clone: yes
    dest: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    repo: "{{ magento2_installation_git_url }}"
    version: "{{ magento2_installation_git_version }}"
  tags: ['git']

- name: Update Magento 2 project.
  become_user: "{{magento2_runtime_user}}"
  composer:
    command: update
    working_dir: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
  tags: ['composer']
