---
# tasks file for memoryleak.magento2
- name: Import initialization tasks.
  import_tasks: initialization.yml
  tags: ['import_tasks']

- name: Include installation method tasks.
  include_tasks: "installation-{{ magento2_installation_method }}.yml"
  tags: ['include_tasks']

- name: Initialize install command string.
  set_fact:
    magento_install_command: "php bin/magento setup:install"

- name: Append arguments to string.
  set_fact:
    magento_install_command: "{{ magento_install_command }} --{{ item.name }}='{{ item.value }}'"
  with_items: "{{ magento2_setup_parameters }}"

- name: Print install command to be used for debugging purposes in case something fails.
  debug:
    var: magento_install_command
  tags: ['debug']

- name: Start Magento 2 installation.
  become_user: "{{magento2_runtime_user}}"
  shell: "{{ magento_install_command }}"
  args:
    chdir: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    executable: php
  tags: ['shell']
  when: magento2_execute_setup

- name: Copy config.php if provided.
  become_user: "{{magento2_runtime_user}}"
  copy:
    dest: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/app/etc/config.php"
    src: "{{ magento2_override_config_file }}"
  tags: ['copy']

- name: Copy env.php if provided.
  become_user: "{{magento2_runtime_user}}"
  copy:
    dest: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/app/etc/env.php"
    src: "{{ magento2_override_config_file }}"
  tags: ['copy']