---
- name: "Set permissions to project sources"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}"
    group: "{{magento2_runtime_group}}"
    owner: "{{magento2_runtime_user}}"
    recurse: yes
    follow: yes
    state: directory
    mode: "u=rX,g=rX,o=rX"

- name: "Set execution mode to Magento binary"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/bin/magento"
    mode: "u=rX,g=r,o=r"

- name: "Fix permissions for app/etc folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/app/etc"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"

- name: "Fix permissions for pub/media folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/pub/media"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"

- name: "Fix permissions for pub/static folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/pub/static"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"

- name: "Fix permissions for var folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/var"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"

- name: "Fix permissions for vendor folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/vendor"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"

- name: "Fix permissions for generated folder"
  file:
    path: "{{ magento2_installation_parent }}/{{ magento2_installation_name }}/generated"
    owner: "{{magento2_runtime_user}}"
    group: "{{magento2_runtime_group}}"
    state: directory
    recurse: yes
    follow: yes
    mode: "u+w"
